## DON'T WORRY ABOUT THIS FILE, IT'S NOT USED IN PRODUCTION

development:
  database: "itmUfx0V6SDGR7dFlD0OY9L6tjJ8Ozb3"
  redis: "qy9NdXpi2bUO60Vk9aokvzfboa3Wf9Nr"
  serviceSecret: "aaNh0G7BYiqyHr7z7DEAP0dV7u74uk-x"

test:
  database: "5ZWKU1TS1-w2OdKWQDFuPRidCES3WVJj"
  redis: "bBZWvtm2f2HvCVXksNQTiMILOma894lI"
